### ISSUE TITLE
Bread box not found

### ISSUE THREAD

**Issue by redsfyre** [tolgaozuygur/cure-o-matic#1]
"Error: the bread box was not found in local stores due to Covid-19. There is no trust in the internet!" What do you suggest I do?

**Comment by wmwmwm** [comment]
Here's some alternatives:

https://www.amazon.com.tr/Homex-S%C3%BCrg%C3%BCl%C3%BC-Ekmeklik-Mor/dp/B07J22DXBG/ref=asc_df_B07J22DXBG/

And you can always use google shopping:
https://www.google.com/search?q=ekmeklik&source=lmns&tbm=shop

**Comment by redsfyre** [comment]
It works for me, thank you
